### ISSUE TITLE
你确定这个RingBuffer多线程 访问安全吗？

### ISSUE THREAD

**Issue by coderlongren** [drneverend/buffers#2]
那个head, tail 至少应该采用AtomicInteger之类 CAS方式来做吧

**Comment by zoyanhui** [comment]
+1

**Comment by drneverend** [comment]
Java中，int的读写是原子操作。参考以下链接

https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html
